name = "KyungminLeeRegistry"
uuid = "ca879cd0-f8f2-11e9-3f8f-f5849d47a06a"
repo = "https://github.com/kyungminlee/KyungminLeeRegistry.jl.git"
description = "Personal registry"

[packages]
f0da6d2f-861b-4198-860c-d50f6f65dfeb = { name = "TightBindingLattice", path = "TightBindingLattice" }
cf149b0a-e8f7-4f00-9ab4-03e4f5ec5cff = { name = "ExactDiagonalization", path = "ExactDiagonalization" }
bb017ab8-e7aa-48c1-8510-d0c63904c71d = { name = "MinimalPerfectHash", path = "MinimalPerfectHash" }
804d6816-852b-11e8-156d-fdb6b2597e74 = { name = "HartreeFockBogoliubov", path = "HartreeFockBogoliubov" }
8a267902-5e0e-44c3-8ef8-9b2b5c352816 = { name = "LatticeTools", path = "LatticeTools" }
7e419fb4-4148-4024-80a8-2502d26d6b11 = { name = "MathExpr", path = "MathExpr" }
76d689ba-cd5d-4c41-ab5a-af133e796eec = { name = "Particle", path = "Particle" }
8f35b48d-05b3-499d-8f31-5fdfb4cc22a8 = { name = "SimpleLinear", path = "SimpleLinear" }