name = "KyungminLeeRegistry"
uuid = "ca879cd0-f8f2-11e9-3f8f-f5849d47a06a"
repo = "https://github.com/kyungminlee/KyungminLeeRegistry.jl.git"
description = "Kyungmin's personal registry"

[packages]
bb017ab8-e7aa-48c1-8510-d0c63904c71d = { name = "MinimalPerfectHash", path = "MinimalPerfectHash" }
804d6816-852b-11e8-156d-fdb6b2597e74 = { name = "HartreeFockBogoliubov", path = "HartreeFockBogoliubov" }
fdaa9585-3dec-4727-b9cf-4a8cf08d7ff9 = { name = "GroupTools", path = "GroupTools" }
8a267902-5e0e-44c3-8ef8-9b2b5c352816 = { name = "LatticeTools", path = "LatticeTools" }
7e419fb4-4148-4024-80a8-2502d26d6b11 = { name = "MathExpr", path = "MathExpr" }
ca2024c7-d5ca-47dc-aafc-db87cbdab76e = { name = "QuantumHamiltonian", path = "QuantumHamiltonian" }
e0af54e9-8e56-4866-a784-1fe532970838 = { name = "QuantumHamiltonianParticle", path = "QuantumHamiltonianParticle" }
3017c631-05ab-49d4-ba00-44a31b8d5f6d = { name = "FiniteTemperatureLanczos", path="FiniteTemperatureLanczos" }
