name: Check packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.5"
      - run: |
          julia -e "using Pkg; Pkg.Registry.add(RegistrySpec(url=\"https://github.com/kyungminlee/KyungminLeeRegistry.jl.git\"))"
          for directory in */
          do
            pkgname="${directory%%/}"
            julia -e "using Pkg; Pkg.add(\"$pkgname\")"
          done
          julia -e "using Pkg; Pkg.precompile()"