name: Check packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1.5"
      - run: julia -e "using Pkg; Pkg.update()"
      - run: julia -e "using Pkg; Pkg.Registry.add(RegistrySpec(url=\"https://github.com/kyungminlee/KyungminLeeRegistry.jl.git\"))"
      - run: julia -e "using Pkg; Pkg.add(\"TOML\")"
      - run: julia .github/workflows/install-packages.jl
      - run: julia -e "using Pkg; Pkg.precompile()"